version: '3.7'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"    # API Port
      - "9001:9001"    # Web Console Port
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminsecret
      MINIO_SERVER_URL: "http://192.168.1.4:9000"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    command: server /data --console-address ":9001"